import cTurtle
import math

def rectangle(turtle, length, width):
        turtle.forward(length)
        turtle.right(90)
        turtle.forward(width)
        turtle.right(90)
        turtle.forward(length)
        turtle.right(90)
        turtle.forward(width)

def polygon(turtle, sides, size=100):
        angle=360/sides
        for i in range(sides):
                turtle.forward(size)
                turtle.right(angle)




def drawNightSky0(turtle):
	turtle.penup()
	turtle.tracer(True)
	turtle.fillcolor(((0/255), (0/255), (100/255)))
	turtle.tracer(False)
	turtle.goto(-1000, 1000) 
	turtle.begin_fill()
	turtle.pendown()
	rectangle(turtle, 2000, 1150)
	turtle.penup()
	turtle.end_fill()
	turtle.hideturtle()
def drawHouse0(turtle):
	turtle.penup()
	turtle.tracer(True)
	turtle.fillcolor(((101/255), (1/255), (42/255)))
	turtle.pencolor("pink")
	turtle.goto(-200, 150) 
	turtle.begin_fill()
	turtle.pendown()
	rectangle(turtle, 400, 300)
	turtle.penup()
	turtle.end_fill()
	turtle.hideturtle()
def drawWindow10(turtle):
	turtle.penup()
	turtle.tracer(True)
	turtle.goto(-100, 100) 
	turtle.fillcolor("orange")
	turtle.begin_fill()
	turtle.pendown()
	polygon(turtle, 12, 17)
	turtle.penup()
	turtle.end_fill()
	turtle.hideturtle()
def drawWindow20(turtle):
	turtle.penup()
	turtle.tracer(True)
	turtle.goto(100, 100) 
	turtle.fillcolor("orange")
	turtle.begin_fill()
	turtle.pendown()
	polygon(turtle, 12, 17)
	turtle.penup()
	turtle.end_fill()
	turtle.hideturtle()
def drawRoof0(turtle):
	turtle.penup()
	turtle.tracer(True)
	turtle.goto(-250, 150) 
	turtle.fillcolor(((135/255), (52/255), (99/255)))
	turtle.begin_fill()
	turtle.pendown()
	turtle.goto(250, 150)
	turtle.goto(0, 200)
	turtle.goto(-250, 150)
	turtle.penup()
	turtle.end_fill()
	turtle.hideturtle()
def drawDoor0(turtle):
	turtle.penup()
	turtle.tracer(True)
	turtle.goto(0, -100) 
	turtle.speed(5)
	turtle.fillcolor("teal")
	turtle.begin_fill()
	turtle.pendown()
	rectangle(turtle, 35, 50)
	turtle.penup()
	turtle.end_fill()
	turtle.hideturtle()
def drawDoorHandle0(turtle):
	turtle.penup()
	turtle.tracer(True)
	turtle.goto(25, -125) 
	turtle.fillcolor("red")
	turtle.begin_fill()
	turtle.pendown()
	rectangle(turtle, 10, 10)
	turtle.penup()
	turtle.end_fill()
	turtle.hideturtle()
def drawGround0(turtle):
	turtle.penup()
	turtle.tracer(True)
	turtle.goto(-1000, -150) 
	turtle.fillcolor(((0/255), (0/255), (0/255)))
	turtle.begin_fill()
	turtle.pendown()
	rectangle(turtle, 2000, 10)
	turtle.penup()
	turtle.end_fill()
	turtle.hideturtle()
def drawMoon0(turtle):
	turtle.penup()
	turtle.tracer(True)
	turtle.goto(-270, 200) 
	turtle.fillcolor("yellow")
	turtle.begin_fill()
	turtle.pendown()
	turtle.circle(50)
	turtle.penup()
	turtle.end_fill()
	turtle.hideturtle()
def main():
	NightSky0=cTurtle.Turtle()
	drawNightSky0(NightSky0)
	House0=cTurtle.Turtle()
	drawHouse0(House0)
	Window10=cTurtle.Turtle()
	drawWindow10(Window10)
	Window20=cTurtle.Turtle()
	drawWindow20(Window20)
	Roof0=cTurtle.Turtle()
	drawRoof0(Roof0)
	Door0=cTurtle.Turtle()
	drawDoor0(Door0)
	DoorHandle0=cTurtle.Turtle()
	drawDoorHandle0(DoorHandle0)
	Ground0=cTurtle.Turtle()
	drawGround0(Ground0)
	Moon0=cTurtle.Turtle()
	drawMoon0(Moon0)

main()
